[2023-08-30T15:49:20.917+0200] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: de_test_workflow.copyPartitionsDataIntoCSVFile manual__2023-08-30T13:43:47.019908+00:00 [queued]>
[2023-08-30T15:49:20.922+0200] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: de_test_workflow.copyPartitionsDataIntoCSVFile manual__2023-08-30T13:43:47.019908+00:00 [queued]>
[2023-08-30T15:49:20.923+0200] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-08-30T15:49:20.932+0200] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): copyPartitionsDataIntoCSVFile> on 2023-08-30 13:43:47.019908+00:00
[2023-08-30T15:49:20.935+0200] {standard_task_runner.py:57} INFO - Started process 7755 to run task
[2023-08-30T15:49:20.940+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'de_test_workflow', 'copyPartitionsDataIntoCSVFile', 'manual__2023-08-30T13:43:47.019908+00:00', '--job-id', '19', '--raw', '--subdir', '/Users/france.cama/code/glovo_de_test/dags/workflows.py', '--cfg-path', '/var/folders/bq/3fzm19j96pq0b42q_ghqb6j40000gn/T/tmp3s_y7iu_']
[2023-08-30T15:49:20.944+0200] {standard_task_runner.py:85} INFO - Job 19: Subtask copyPartitionsDataIntoCSVFile
[2023-08-30T15:49:21.005+0200] {task_command.py:415} INFO - Running <TaskInstance: de_test_workflow.copyPartitionsDataIntoCSVFile manual__2023-08-30T13:43:47.019908+00:00 [running]> on host mba-francesco.local
[2023-08-30T15:49:21.080+0200] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='francesco' AIRFLOW_CTX_DAG_ID='de_test_workflow' AIRFLOW_CTX_TASK_ID='copyPartitionsDataIntoCSVFile' AIRFLOW_CTX_EXECUTION_DATE='2023-08-30T13:43:47.019908+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-30T13:43:47.019908+00:00'
[2023-08-30T15:49:21.081+0200] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/bq/3fzm19j96pq0b42q_ghqb6j40000gn/T
[2023-08-30T15:49:21.082+0200] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cat /Users/france.cama/code/glovo_de_test/output_dataset/*.csv >> /Users/france.cama/code/glovo_de_test/output_dataset/single_output_dataset.csv']
[2023-08-30T15:49:21.085+0200] {subprocess.py:86} INFO - Output:
[2023-08-30T15:51:06.690+0200] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-08-30T15:51:06.796+0200] {process_utils.py:131} INFO - Sending 15 to group 7755. PIDs of all processes in the group: [7756, 7757, 7755]
[2023-08-30T15:51:06.796+0200] {process_utils.py:86} INFO - Sending the signal 15 to group 7755
[2023-08-30T15:51:06.797+0200] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-08-30T15:51:06.798+0200] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2023-08-30T15:51:06.851+0200] {process_utils.py:79} INFO - Process psutil.Process(pid=7756, status='terminated', started='15:49:21') (7756) terminated with exit code None
[2023-08-30T15:51:06.908+0200] {process_utils.py:79} INFO - Process psutil.Process(pid=7757, status='terminated', started='15:49:21') (7757) terminated with exit code None
[2023-08-30T15:51:06.908+0200] {process_utils.py:79} INFO - Process psutil.Process(pid=7755, status='terminated', exitcode=0, started='15:49:20') (7755) terminated with exit code 0
