[2023-08-30T15:51:43.373+0200] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: de_test_workflow.copyPartitionsDataIntoCSVFile manual__2023-08-30T13:51:23.013405+00:00 [queued]>
[2023-08-30T15:51:43.377+0200] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: de_test_workflow.copyPartitionsDataIntoCSVFile manual__2023-08-30T13:51:23.013405+00:00 [queued]>
[2023-08-30T15:51:43.377+0200] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-08-30T15:51:43.384+0200] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): copyPartitionsDataIntoCSVFile> on 2023-08-30 13:51:23.013405+00:00
[2023-08-30T15:51:43.386+0200] {standard_task_runner.py:57} INFO - Started process 7834 to run task
[2023-08-30T15:51:43.388+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'de_test_workflow', 'copyPartitionsDataIntoCSVFile', 'manual__2023-08-30T13:51:23.013405+00:00', '--job-id', '22', '--raw', '--subdir', '/Users/france.cama/code/glovo_de_test/dags/workflows.py', '--cfg-path', '/var/folders/bq/3fzm19j96pq0b42q_ghqb6j40000gn/T/tmpbdr6zqyq']
[2023-08-30T15:51:43.389+0200] {standard_task_runner.py:85} INFO - Job 22: Subtask copyPartitionsDataIntoCSVFile
[2023-08-30T15:51:43.432+0200] {task_command.py:415} INFO - Running <TaskInstance: de_test_workflow.copyPartitionsDataIntoCSVFile manual__2023-08-30T13:51:23.013405+00:00 [running]> on host mba-francesco.local
[2023-08-30T15:51:43.493+0200] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='francesco' AIRFLOW_CTX_DAG_ID='de_test_workflow' AIRFLOW_CTX_TASK_ID='copyPartitionsDataIntoCSVFile' AIRFLOW_CTX_EXECUTION_DATE='2023-08-30T13:51:23.013405+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-30T13:51:23.013405+00:00'
[2023-08-30T15:51:43.493+0200] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/bq/3fzm19j96pq0b42q_ghqb6j40000gn/T
[2023-08-30T15:51:43.494+0200] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cat /Users/france.cama/code/glovo_de_test/output_dataset/*.csv >> /Users/france.cama/code/glovo_de_test/output_dataset/single_output_dataset.csv']
[2023-08-30T15:51:43.497+0200] {subprocess.py:86} INFO - Output:
[2023-08-30T15:55:20.146+0200] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-08-30T15:55:20.164+0200] {process_utils.py:131} INFO - Sending 15 to group 7834. PIDs of all processes in the group: [7835, 7836, 7834]
[2023-08-30T15:55:20.164+0200] {process_utils.py:86} INFO - Sending the signal 15 to group 7834
[2023-08-30T15:55:20.165+0200] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-08-30T15:55:20.166+0200] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2023-08-30T15:55:20.219+0200] {process_utils.py:79} INFO - Process psutil.Process(pid=7834, status='terminated', exitcode=0, started='15:51:43') (7834) terminated with exit code 0
[2023-08-30T15:55:20.221+0200] {process_utils.py:79} INFO - Process psutil.Process(pid=7835, status='terminated', started='15:51:43') (7835) terminated with exit code None
[2023-08-30T15:55:20.360+0200] {process_utils.py:79} INFO - Process psutil.Process(pid=7836, status='terminated', started='15:51:43') (7836) terminated with exit code None
